doubleclick-config:
  google-geo-path: './data/google-geo-table.csv'
  vpon-geo-path: './data/geography.xlsx'
  hk-google-vpon-geo-path: './data/geography-HK-google2Vpon.xlsx'
  prebid_path: './data/prebid_data.csv'

ftp-config:
  ip: '10.0.1.3'
  username: 'adnext'
  password: '28892170'
